PPU-33e09a0bd8fa2a3b28780a3feeb7b0e018bae381:
  Unlock FPS:
    "Metal Gear Solid 4: Guns of the Patriots":
      BLUS30109:
        02.00:
          Enabled: true
  Crash fix:
    "Metal Gear Solid 4: Guns of the Patriots":
      BLUS30109:
        02.00:
          Enabled: true