name: Deploy to Public Repo

on:
  push:
    branches:
      - public

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: public
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Push to public repository
        run: |
          git remote add casstanje-shell https://github.com/casstanje/casstanje-shell.git
          git push -f casstanje-shell public:main --force
